version: '3'
services:
  carg-db:
    image: postgres
    restart: always
    ports: 
      - "2020:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 3
